/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nrims.managers;

import com.nrims.CompositeProps;
import com.nrims.HSIProps;
import com.nrims.MassProps;
import com.nrims.MimsRoiManager2;
import com.nrims.RatioProps;
import com.nrims.SumProps;
import com.nrims.UI;
import ij.gui.Roi;
import java.awt.Color;
import java.awt.Cursor;
import java.io.File;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Vector;

import javax.swing.DefaultComboBoxModel;

import javax.swing.WindowConstants;

/**
 *
 * @author djsia
 */
public class FilesManager extends javax.swing.JFrame {

    static final public int FILE_SETTINGS = 0;
    static final public int LAST_FILE_SETTINGS = 1;
    static final public int DEFAULT_SETTINGS = 2;

    static javax.swing.JFrame instance;
    private DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    private UI ui;
    private String chosenFile = "";
    private int chosenSettings;
    private boolean LoadFileProcessStopped = false;

    // Dj; 08/20/2014
    /**
     * Creates new form FilesManager
     *  
     * @param ui a reference to the <code>ui</code> instance.
     * @param filesPreviouslyOpened tbd.
     * @param LoadFileProcessStopped tbd.
     * @param openedFilePath tbd.
     * 
     */
    public FilesManager(UI ui, String[] filesPreviouslyOpened, boolean LoadFileProcessStopped, String openedFilePath) {

        initComponents();
        this.ui = ui;

        this.LoadFileProcessStopped = LoadFileProcessStopped;

        if (filesPreviouslyOpened == null) {
            filesPreviouslyOpened = new String[0];
        }

        if (LoadFileProcessStopped == false) {
            info_Label.setText("");
            jSeparator1.setVisible(false);
            jSeparator1.setVisible(false);

            openedFileInfoLabel.setVisible(true);

            openedFileLabel.setText(openedFilePath);
            openedFileLabel.setForeground(Color.BLUE);
            openedFileLabel.setVisible(true);

            jSeparator3.setVisible(true);
        } else {
            info_Label.setText("STATUS: LOADING FILE PROCESS STOPPED.");
            jSeparator1.setVisible(true);
            jSeparator2.setVisible(true);

            openedFileLabel.setVisible(false);
            openedFileInfoLabel.setVisible(false);
            jSeparator3.setVisible(false);
        }

        files_jComboBox.setModel(comboBoxModel);
        chosenSettings = FILE_SETTINGS;
        rb0.setActionCommand("0");
        rb1.setActionCommand("1");
        rb2.setActionCommand("2");

        rb0.setSelected(true);
        this.setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        addImageFiles(filesPreviouslyOpened);

        //DJ:09/06/2014
        if (filesPreviouslyOpened.length == 0) {
            reload_button.setEnabled(false);
            cancel_button.setEnabled(false);
        }

        instance = this;
    }

    //Dj: 08/20/2014
    /**
     * Gets an instance of the FileManager Frame
     *
     * @return an instance of this FileManager Frame.
     */
    public static FilesManager getInstance() {
        return (FilesManager) instance;
    }

    //DJ: 08/20/2014
    /**
     * closes the FileManger Frame by disposing it.
     */
    public void closeWindow() {
        super.dispose();
    }

    // DJ: 08/01/2014
    /**
     * Shows the FileManager Frame by setting the visibility to <code>true</code>
     */
    public void showWindow() {
        this.setVisible(true);
    }

    public void activate_disactivate_components() {

        if (comboBoxModel == null || comboBoxModel.getSize() == 0) {
            rb0.setEnabled(false);
            rb1.setEnabled(false);
            rb2.setEnabled(false);

            reload_button.setEnabled(false);
            cancel_button.setEnabled(false);
        } else {
            rb0.setEnabled(true);
            rb1.setEnabled(true);
            rb2.setEnabled(true);

            reload_button.setEnabled(true);
            cancel_button.setEnabled(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        radioButtonsGroup = new javax.swing.ButtonGroup();
        info_Label = new javax.swing.JLabel();
        filesList_jLabel = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        rb0 = new javax.swing.JRadioButton();
        rb1 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        reload_button = new javax.swing.JButton();
        cancel_button = new javax.swing.JButton();
        files_jComboBox = new javax.swing.JComboBox();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        openedFileLabel = new javax.swing.JLabel();
        openedFileInfoLabel = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Files Manager");

        info_Label.setForeground(new java.awt.Color(248, 19, 26));
        info_Label.setText("STATUS: LOADING FILE PROCESS STOPPED.");

        filesList_jLabel.setText("LIST OF FILES PREVIOUSLY OPENED (Latest file first) : ");

        radioButtonsGroup.add(rb2);
        rb2.setText("Default Settings (open as new)");

        radioButtonsGroup.add(rb0);
        rb0.setText("File Settings");

        radioButtonsGroup.add(rb1);
        rb1.setText("Last File Settings");

        jLabel3.setText("Re-Load with : ");

        reload_button.setText("RELOAD");
        reload_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reload_buttonActionPerformed(evt);
            }
        });

        cancel_button.setText("CANCEL");
        cancel_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancel_buttonActionPerformed(evt);
            }
        });

        files_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        openedFileLabel.setText("jLabel1");

        openedFileInfoLabel.setText("ACTUAL OPENED FILE IS: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(info_Label, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(221, 221, 221)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rb0)
                            .addComponent(rb2)
                            .addComponent(rb1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(203, 203, 203)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(files_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(filesList_jLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 801, Short.MAX_VALUE)
                            .addComponent(openedFileInfoLabel)
                            .addComponent(openedFileLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(reload_button)
                        .addGap(26, 26, 26)
                        .addComponent(cancel_button)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(info_Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openedFileInfoLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openedFileLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(filesList_jLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(files_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reload_button)
                            .addComponent(cancel_button))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(rb0)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rb2)
                        .addGap(31, 31, 31))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents


    private void cancel_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancel_buttonActionPerformed

        if (LoadFileProcessStopped == true) {
            restoreLastOpenedFile();
        }

        closeWindow();

    }//GEN-LAST:event_cancel_buttonActionPerformed

    private void reload_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reload_buttonActionPerformed

        chosenFile = comboBoxModel.getSelectedItem().toString();
        chosenSettings = Integer.parseInt(radioButtonsGroup.getSelection().getActionCommand());

        try {
            //------------------------------------------------------ 
            if (chosenSettings == FilesManager.FILE_SETTINGS) {
                reOpenWithFileSettings(chosenFile);
            }//------------------------------------------------------ 
            else if (chosenSettings == FilesManager.LAST_FILE_SETTINGS) {
                reOpenWithLastFileSettings(chosenFile);
            }//------------------------------------------------------
            else if (chosenSettings == FilesManager.DEFAULT_SETTINGS) {
                reOpenWithDefaultSettings(chosenFile);
            }

        } finally {
            setCursor(null);
        }

        //  this.dispose();
    }//GEN-LAST:event_reload_buttonActionPerformed

    public void addImageFiles(String[] imageFilesNames) {

        if (imageFilesNames == null) {
            return;
        }
        // loop in inverse in order to show the latest file opened first.
        for (int i = imageFilesNames.length - 1; i >= 0; i--) {
            File file = new File(imageFilesNames[i]);
            if (file.exists()) // test just in case the file gets deleted manually by user.
            {
                comboBoxModel.addElement(imageFilesNames[i]);
            }
        }
    }

    public void removeImagefromList(String imageFileName) {
        if (imageFileName == null) {
            return;
        }
        int indexToBeRemoved = -1;
        for (int i = 0; i <= comboBoxModel.getSize(); i++) {
            if (((String) (comboBoxModel.getElementAt(i))).equals(imageFileName)) {
                indexToBeRemoved = i;
                break;
            }
        }
        if (indexToBeRemoved == -1) {
            return;
        }

        comboBoxModel.removeElementAt(indexToBeRemoved);
        ui.removeFileFromFileProps(imageFileName);
        files_jComboBox.repaint();

    }

    // DJ: 08/21/2014
    /**
     * ReOpens the last non-canceled file with its settings, derived images, and ROIs
     */
    private void restoreLastOpenedFile() {
        //  reOpenWithLastFileSettings(ui.getNameOfLastFileOpened());
        reOpenWithFileSettings(ui.getNameOfLastFileOpened());
        closeWindow(); //DJ: 09/24/2014
    }

    // DJ: 08/21/2014
    /**
     * ReOpens the file with the default settings No derived images and no ROIs (CLEAN COPY)
     *
     * @param chosenFile
     */
    private void reOpenWithDefaultSettings(String chosenFile) {

        File previousFileToLoad = new File(chosenFile);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        com.nrims.UI.FileOpenTask fileOpenTask;
        fileOpenTask = ui.new FileOpenTask(previousFileToLoad, ui);

        boolean opened = fileOpenTask.doInBackground(null, null, null, null, null, false, false);
        ui.resetRoiManager();

        removeImagefromList(chosenFile);
        closeWindow(); //DJ: 09/24/2014
    }

    // DJ: 08/21/2014
    /**
     * ReOpens the file with the last settings, derived images, and ROIs of this specific file before it was closed.
     *
     * @param chosenFile
     */
    private void reOpenWithFileSettings(String chosenFile) {

        File previousFileToLoad = new File(chosenFile);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        com.nrims.UI.FileOpenTask fileOpenTask;
        fileOpenTask = ui.new FileOpenTask(previousFileToLoad, ui);

        Vector allProps = ui.getFileSettings(chosenFile);

        //------------------------------------
        MassProps[] massP = (MassProps[]) (allProps.get(0));
        RatioProps[] ratioP = (RatioProps[]) (allProps.get(1));
        HSIProps[] hsiP = (HSIProps[]) (allProps.get(2));
        SumProps[] sumP = (SumProps[]) (allProps.get(3));
        CompositeProps[] compP = (CompositeProps[]) (allProps.get(4));

        //------------------------------------
        ArrayList<Object> roiProps = (ArrayList<Object>) (allProps.get(6));

        boolean isROIManagerVisible = (Boolean) (roiProps.get(0));
        Roi[] roiList = (Roi[]) (roiProps.get(1));
        HashMap<String, ArrayList<Integer[]>> locations = (HashMap<String, ArrayList<Integer[]>>) (roiProps.get(2));
        ArrayList<String> groups = (ArrayList<String>) (roiProps.get(3));
        HashMap<String, String> groupsMap = (HashMap<String, String>) (roiProps.get(4));
        //------------------------------------
        boolean opened = fileOpenTask.doInBackground(
                massP, ratioP, hsiP, sumP, compP, false, false);

        //-------------------------------------
        if ((Boolean) (allProps.get(5)) == true) {
            com.nrims.managers.CompositeManager cm = new com.nrims.managers.CompositeManager(ui);
            cm.setVisible(true);
        }
        //------------------------------------
        ui.resetRoiManager();
        
        MimsRoiManager2 roiManager = ui.getRoiManager();
        for (String group : groups) {
            //ui.getRoiManager().addGroup(group);
            //roiManager.addGroup(groupName, groupType);
        }

        for (int i = 0; i < roiList.length; i++) {
            if (groupsMap.keySet().contains(roiList[i].getName())) {
                //ui.getRoiManager().addToGroupWithoutRenaming(roiList[i], groupsMap.get(roiList[i].getName()));
              //  MimsRoiManager2.ROIgroup group = roiManager.new ROIgroup(groupName,
               //                         roiManager.GROUPTYPE_SEGMENTATION_TRAINING);
               // roiManager.addToGroupWithoutRenaming(roiList[i], groupsMap.get(roiList[i].getName()));
            } else {
                roiManager.addWithoutRenaming(roiList[i]);
            }
        }
        ui.getRoiManager().setLocations(locations);
        ui.getRoiManager().setVisible(isROIManagerVisible);

        removeImagefromList(chosenFile);

        closeWindow(); //DJ: 09/24/2014
    }

    // DJ: 08/21/2014
    /**
     * ReOpens the file with the settings, derived images, and ROIs of the last fully opened file.
     *
     * @param chosenFile
     */
    private void reOpenWithLastFileSettings(String chosenFile) {

        File previousFileToLoad = new File(chosenFile);
        setCursor(Cursor.getPredefinedCursor(Cursor.WAIT_CURSOR));
        com.nrims.UI.FileOpenTask fileOpenTask;
        fileOpenTask = ui.new FileOpenTask(previousFileToLoad, ui);

        Vector allProps = ui.getFileSettings(ui.getNameOfLastFileOpened());

        //------------------------------------
        MassProps[] massP = (MassProps[]) (allProps.get(0));
        RatioProps[] ratioP = (RatioProps[]) (allProps.get(1));
        HSIProps[] hsiP = (HSIProps[]) (allProps.get(2));
        SumProps[] sumP = (SumProps[]) (allProps.get(3));
        CompositeProps[] compP = (CompositeProps[]) (allProps.get(4));

        //------------------------------------
        ArrayList<Object> roiProps = (ArrayList<Object>) (allProps.get(6));

        boolean isROIManagerVisible = (Boolean) (roiProps.get(0));
        /*
        Roi[] roiList = (Roi[]) (roiProps.get(1));
        HashMap<String, ArrayList<Integer[]>> locations = (HashMap<String, ArrayList<Integer[]>>) (roiProps.get(2));
        ArrayList<String> groups = (ArrayList<String>) (roiProps.get(3));
        HashMap<String, String> groupsMap = (HashMap<String, String>) (roiProps.get(4));
         */
        //------------------------------------
        boolean opened = fileOpenTask.doInBackground(
                massP, ratioP, hsiP, sumP, compP, false, isROIManagerVisible);

        //-------------------------------------
        if ((Boolean) (allProps.get(5)) == true) {
            com.nrims.managers.CompositeManager cm = new com.nrims.managers.CompositeManager(ui);
            cm.setVisible(true);
        }

        removeImagefromList(chosenFile);

        closeWindow(); //DJ: 09/24/2014
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancel_button;
    private javax.swing.JLabel filesList_jLabel;
    private javax.swing.JComboBox files_jComboBox;
    private javax.swing.JLabel info_Label;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel openedFileInfoLabel;
    private javax.swing.JLabel openedFileLabel;
    private javax.swing.ButtonGroup radioButtonsGroup;
    private javax.swing.JRadioButton rb0;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JButton reload_button;
    // End of variables declaration//GEN-END:variables
}
