/*
 * mimsRoiControl.java
 *
 * Created on May 3, 2006, 9:57 AM
 */

package com.nrims;

import ij.*;
import ij.process.*;
import ij.gui.*;
import java.awt.*;

import com.nrims.UI;
import ij.plugin.filter.RGBStackSplitter;
import ij.gui.Roi;
import ij.process.FloatProcessor;
import ij.process.ImageProcessor;
import ij.process.ShortProcessor;
import java.awt.Frame;
import java.util.ArrayList;
import java.io.BufferedWriter;
import java.io.FileWriter;
import java.util.Enumeration;
import javax.swing.JFileChooser;
/**
 *
 * @author  Douglas Benson
 */
public class MimsRoiControl extends javax.swing.JPanel {
    
    /**
     * Creates new form mimsRoiControl
     */
    public MimsRoiControl(UI ui) {
        this.ui = ui ;
        measure = new Measure(ui);
        initComponents();        
        
        jCheckBox2.setSelected(ui.getSyncROIs());
        jCheckBox3.setSelected(ui.getAddROIs());
        jCheckBox5.setSelected(ui.getSyncROIsAcrossPlanes());
        jTextField1.setText(ui.getMimsImage().getImageFile().getName()+".txt");
        measure.setName(jTextField1.getText());
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jCheckBox2 = new javax.swing.JCheckBox();
      jCheckBox3 = new javax.swing.JCheckBox();
      jButton1 = new javax.swing.JButton();
      jButton2 = new javax.swing.JButton();
      jButton3 = new javax.swing.JButton();
      jButton4 = new javax.swing.JButton();
      jCheckBox4 = new javax.swing.JCheckBox();
      jLabel1 = new javax.swing.JLabel();
      jTextField1 = new javax.swing.JTextField();
      jButton5 = new javax.swing.JButton();
      jCheckBox5 = new javax.swing.JCheckBox();
      contrastAdjuster1 = new com.nrims.ContrastAdjuster();
      jSeparator1 = new javax.swing.JSeparator();
      jLabel2 = new javax.swing.JLabel();

      setToolTipText("Drawing ROIs automatically adds to RoiManager");

      jCheckBox2.setText("Synchronize ROIs across all masses");
      jCheckBox2.setToolTipText("Display ROI in all images");
      jCheckBox2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
      jCheckBox2.setMargin(new java.awt.Insets(0, 0, 0, 0));
      jCheckBox2.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCheckBox2ItemStateChanged(evt);
         }
      });

      jCheckBox3.setText("Add ROIs");
      jCheckBox3.setToolTipText("Automatically add ROs to the RoiManager");
      jCheckBox3.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
      jCheckBox3.setMargin(new java.awt.Insets(0, 0, 0, 0));
      jCheckBox3.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCheckBox3ItemStateChanged(evt);
         }
      });

      jButton1.setText("RoiManager");
      jButton1.setToolTipText("Launch RoiManager");
      jButton1.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
         }
      });

      jButton2.setText("Measure All Rois");
      jButton2.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton2ActionPerformed(evt);
         }
      });

      jButton3.setText("Data Options...");
      jButton3.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton3ActionPerformed(evt);
         }
      });

      jButton4.setText("Source images...");
      jButton4.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton4ActionPerformed(evt);
         }
      });

      jCheckBox4.setText("Append to table");
      jCheckBox4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
      jCheckBox4.setMargin(new java.awt.Insets(0, 0, 0, 0));

      jLabel1.setText("Table Name");

      jTextField1.setText("NRIMS.txt");
      jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
         public void keyPressed(java.awt.event.KeyEvent evt) {
            jTextField1KeyPressed(evt);
         }
      });

      jButton5.setText("Measure Sum Images");
      jButton5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton5ActionPerformed(evt);
         }
      });

      jCheckBox5.setText("Synchronize ROIs across all planes ");
      jCheckBox5.setToolTipText("Display ROI in all images");
      jCheckBox5.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
      jCheckBox5.setMargin(new java.awt.Insets(0, 0, 0, 0));
      jCheckBox5.addItemListener(new java.awt.event.ItemListener() {
         public void itemStateChanged(java.awt.event.ItemEvent evt) {
            jCheckBox5ItemStateChanged(evt);
         }
      });
      jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            jCheckBox5ActionPerformed(evt);
         }
      });

      jSeparator1.setForeground(new java.awt.Color(153, 153, 255));
      jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
      jSeparator1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
      jSeparator1.setOpaque(true);

      jLabel2.setText("Brightness / Contrast");

      org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(layout.createSequentialGroup()
                  .add(jCheckBox3)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                  .add(jButton1))
               .add(layout.createSequentialGroup()
                  .add(jLabel1)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 144, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
               .add(jCheckBox5)
               .add(jCheckBox2)
               .add(jCheckBox4)
               .add(layout.createSequentialGroup()
                  .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 138, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                  .add(12, 12, 12)
                  .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
               .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                  .add(org.jdesktop.layout.GroupLayout.LEADING, jButton3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                  .add(org.jdesktop.layout.GroupLayout.LEADING, jButton4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(77, 77, 77)
            .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
            .add(31, 31, 31)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(jLabel2)
               .add(contrastAdjuster1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .add(44, 44, 44))
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
         .add(layout.createSequentialGroup()
            .add(12, 12, 12)
            .add(jCheckBox5)
            .add(18, 18, 18)
            .add(jCheckBox2)
            .add(16, 16, 16)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jCheckBox3)
               .add(jButton1))
            .add(51, 51, 51)
            .add(jButton4)
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
            .add(jButton3)
            .add(12, 12, 12)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
               .add(jLabel1)
               .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
               .add(jButton5)
               .add(jButton2))
            .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
            .add(jCheckBox4)
            .add(27, 27, 27))
         .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
            .addContainerGap()
            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
               .add(org.jdesktop.layout.GroupLayout.LEADING, jSeparator1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
               .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                  .add(jLabel2)
                  .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                  .add(contrastAdjuster1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)))
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyChar() == '\t' || evt.getKeyChar() == '\n')
            measure.setName(jTextField1.getText());
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        measure.getSourceOptions();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        measure.getDataOptions();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        // If not appending reset the data in the table
        if(!jCheckBox4.isSelected()) 
           measure.reset();
        
        if(jCheckBox5.isSelected()) 
           measure.generateStackTable();
        else 
           measure.generateRoiTable();
        ij.WindowManager.getFrame(measure.getName()).setSize(450, 300);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ui.getRoiManager().showFrame();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox3ItemStateChanged
        ui.setAddROIs(jCheckBox3.isSelected());
    }//GEN-LAST:event_jCheckBox3ItemStateChanged

    private void jCheckBox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox2ItemStateChanged
        ui.setSyncROIs(jCheckBox2.isSelected());
    }//GEN-LAST:event_jCheckBox2ItemStateChanged

private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
// TODO add your handling code here:
    // If not appending reset the data in the table
    if(jCheckBox4.isSelected() == false ) measure.reset();
    measure.measureSums();
    
    if (ij.WindowManager.getFrame(measure.getName()) != null) {
        ij.WindowManager.getFrame(measure.getName()).setSize(450, 300);
        ij.WindowManager.getFrame(measure.getName());
    }
}//GEN-LAST:event_jButton5ActionPerformed

private void jCheckBox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCheckBox5ItemStateChanged
// TODO add your handling code here:   
   ui.setSyncROIsAcrossPlanes(jCheckBox5.isSelected());
   WindowManager.getCurrentImage().updateAndRepaintWindow();   
   //WindowManager.repaintImageWindows();
}//GEN-LAST:event_jCheckBox5ItemStateChanged

public void setROIsSynchedAcrossPlanes(boolean setSynched) {
   jCheckBox5.setSelected(setSynched);
}

private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_jCheckBox5ActionPerformed
   
public ContrastAdjuster getContrastAdjuster() {
   return this.contrastAdjuster1;
}
    private com.nrims.UI ui = null ;
    private com.nrims.Measure measure = null ;
    
   // Variables declaration - do not modify//GEN-BEGIN:variables
   private com.nrims.ContrastAdjuster contrastAdjuster1;
   private javax.swing.JButton jButton1;
   private javax.swing.JButton jButton2;
   private javax.swing.JButton jButton3;
   private javax.swing.JButton jButton4;
   private javax.swing.JButton jButton5;
   private javax.swing.JCheckBox jCheckBox2;
   private javax.swing.JCheckBox jCheckBox3;
   private javax.swing.JCheckBox jCheckBox4;
   private javax.swing.JCheckBox jCheckBox5;
   private javax.swing.JLabel jLabel1;
   private javax.swing.JLabel jLabel2;
   private javax.swing.JSeparator jSeparator1;
   private javax.swing.JTextField jTextField1;
   // End of variables declaration//GEN-END:variables
    
}
