/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nrims.unoplugin;

import ij.IJ;
import ij.ImageJ;
import ij.WindowManager;
import java.awt.Image;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;

/**
 *
 * @author wang2
 */
public class UnoPluginWindow extends javax.swing.JFrame{
    private UnoPlugin unoPlugin;
    /**
     * Creates new form UnoPluginWindow
     */
    public UnoPluginWindow(String title, UnoPlugin unoPlugin) {
        super(title);
        initComponents();
        ImageJ iij = IJ.getInstance();
        if (iij != null) {
            Image img = iij.getIconImage();
            if (img != null) {
                try {
                    setIconImage(img);
                } catch (Exception e) {
                }
            }
        }
        this.unoPlugin = unoPlugin;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        openNewWriterButton = new javax.swing.JButton();
        insertOLEButton = new javax.swing.JButton();
        autoTileRadio = new javax.swing.JRadioButton();
        autoResizeRadio = new javax.swing.JRadioButton();
        dropResizeRadio = new javax.swing.JRadioButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        openNewWriterButton.setText("Open New Writer Doc");
        openNewWriterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNewWriterButtonActionPerformed(evt);
            }
        });

        insertOLEButton.setText("Insert OLE Frame");
        insertOLEButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertOLEButtonActionPerformed(evt);
            }
        });

        autoTileRadio.setSelected(true);
        autoTileRadio.setText("Auto tile");
        autoTileRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoTileRadioActionPerformed(evt);
            }
        });

        autoResizeRadio.setSelected(true);
        autoResizeRadio.setText("Resize to window");
        autoResizeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                autoResizeRadioActionPerformed(evt);
            }
        });

        dropResizeRadio.setSelected(true);
        dropResizeRadio.setText("Resize on drop");
        dropResizeRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropResizeRadioActionPerformed(evt);
            }
        });

        jLabel1.setText("Options");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dropResizeRadio)
                    .addComponent(autoTileRadio)
                    .addComponent(autoResizeRadio))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(insertOLEButton)
                            .addGap(45, 45, 45))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(openNewWriterButton)
                            .addContainerGap()))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(openNewWriterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(insertOLEButton)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoResizeRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(autoTileRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dropResizeRadio)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void openNewWriterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNewWriterButtonActionPerformed
        UnoPlugin.newDoc();
    }//GEN-LAST:event_openNewWriterButtonActionPerformed

    private void insertOLEButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertOLEButtonActionPerformed
       UnoPlugin.insertEmptyOLEObject("", "");
    }//GEN-LAST:event_insertOLEButtonActionPerformed

    private void autoResizeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoResizeRadioActionPerformed
        unoPlugin.fitToWindow = autoResizeRadio.isSelected();
    }//GEN-LAST:event_autoResizeRadioActionPerformed

    private void autoTileRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_autoTileRadioActionPerformed
        unoPlugin.autoTile = autoTileRadio.isSelected();
    }//GEN-LAST:event_autoTileRadioActionPerformed

    private void dropResizeRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropResizeRadioActionPerformed
        unoPlugin.dropToResize = dropResizeRadio.isSelected();
    }//GEN-LAST:event_dropResizeRadioActionPerformed
    
   
    /** Closes this window. */
    public void close() {      
        setVisible(false);
        dispose();
        WindowManager.removeWindow(this);
    }
    public boolean autoResize(){
        return autoResizeRadio.isSelected();
    }
    public boolean autoTile(){
        return autoTileRadio.isSelected();
    }
    public boolean dropResize(){
        return dropResizeRadio.isSelected();
    }
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton autoResizeRadio;
    private javax.swing.JRadioButton autoTileRadio;
    private javax.swing.JRadioButton dropResizeRadio;
    private javax.swing.JButton insertOLEButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton openNewWriterButton;
    // End of variables declaration//GEN-END:variables
}
