#!/bin/bash
#
###########################################################
## ZK, Nov 2 2011:
## Use this script to open a multi instance of the plugin.
## The "-imfile" flag is not necessary, but I have left it 
## for clarity. 
###########################################################
/nrims/common/local/ImageJ/runUI -imfile "$@"
