package com.nrims;

/**
 * The MimsLog class provides a text area for appending notes or debug data, or any kind of data the programmer wishes
 * to include. This text area is provided in the "Log" tab of the user interface.
 *
 * @author cpoczatek
 */
public class MimsLog extends javax.swing.JPanel {

    /**
     * Creates new form mimsLog
     */
    public MimsLog() {
        initComponents();
    }

    /**
     * Appends data to the log.
     *
     * @param entry the entry to be appended.
     */
    public void Log(String entry) {
        jTextArea1.append(entry);
        jTextArea1.append("\n");
    }

    /**
     * Clears the log.
     */
    public void Clear() {
        jTextArea1.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The
     * content of this method is always regenerated by the Form Editor.
     */
   // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      jScrollPane1 = new javax.swing.JScrollPane();
      jTextArea1 = new javax.swing.JTextArea();
      clearButton = new javax.swing.JButton();

      jTextArea1.setColumns(20);
      jTextArea1.setRows(5);
      jTextArea1.setMaximumSize(new java.awt.Dimension(250, 300));
      jScrollPane1.setViewportView(jTextArea1);

      clearButton.setText("Clear Log");
      clearButton.addActionListener(new java.awt.event.ActionListener() {
         public void actionPerformed(java.awt.event.ActionEvent evt) {
            clearButtonActionPerformed(evt);
         }
      });

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
      this.setLayout(layout);
      layout.setHorizontalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
               .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
               .addComponent(clearButton))
            .addContainerGap())
      );
      layout.setVerticalGroup(
         layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
         .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(clearButton)
            .addContainerGap())
      );
   }// </editor-fold>//GEN-END:initComponents

    /**
     * Action to be performed when "clear" button pressed. All text in textArea it deleted.
     */
private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
    this.Clear();
}//GEN-LAST:event_clearButtonActionPerformed

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton clearButton;
   private javax.swing.JScrollPane jScrollPane1;
   private javax.swing.JTextArea jTextArea1;
   // End of variables declaration//GEN-END:variables
}
